### ISSUE TITLE
ArcGIS Desktop Plugin - EDrive

### ISSUE THREAD

**Issue by meghamahant** [ellipsis-drive/arcgis-plugin#1]
**Testing** - Round 1
**ArcMap version** - 10.8.2

1. When I open the “My Drive” folder, there is no visual difference between the folder and the map.  It is not possible to know which content in the list is a folder and which is a map. 
Is it possible to support the list items with an icon ?

![Screenshot 2022-07-06 at 5 34 32 PM](https://user-images.githubusercontent.com/74825925/177546064-48eeb287-d468-43cc-9731-def482a67aa4.png)

2. While taking the steps to view the raster map, only WMTS option is shown in the list and not WMS and WCS ? Is there any reason behind it ? Are we only supporting WMTS intentionally ?

3. When we double click on WMTS option to view the raster, the system takes some time to load the layer in the LAYER panel. Can we show some signal (a loader etc.) next to the WMTS to hint the user to wait.... ?

**Comment by B-Starkenburg** [comment]
Added visual difference between the folder and the maps

**Comment by meghamahant** [comment]
@B-Starkenburg 

I am not noticing any visual difference between a folder and a raster/vector layer after the update. Could you have a look again please what could be the reason for this ?

Example :
![Screenshot 2023-01-09 at 12 41 38 PM](https://user-images.githubusercontent.com/74825925/211256806-98d8a597-df88-464c-a342-2124ccbe1a53.png)

### Web App
![Screenshot 2023-01-09 at 12 42 16 PM](https://user-images.githubusercontent.com/74825925/211256813-2b3348a7-b7a0-42d9-bac7-03c17ae4d7a5.png)

**Comment by B-Starkenburg** [comment]
I forgot to update the esri addin installer. It should look something like this:
![image](https://user-images.githubusercontent.com/55835594/211284324-c1a5abd3-db23-4a36-95b2-95efabd51bee.png)

**Comment by meghamahant** [comment]
@B-Starkenburg 

Point 1 is ok.
Could you please assist around point 2 and point 3 ?

**Comment by B-Starkenburg** [comment]
For point 2, as agreed with Daan, we have chosen to only support WMS and WMTS layers because of difficulties adding WCS layers.
For point 3, I will implement this at the same time as the refresh button.

**Comment by B-Starkenburg** [comment]
The waiting cursor is implemented
