### ISSUE TITLE
EDrive - A folder that is shared privately cannot be viewed

### ISSUE THREAD

**Issue by meghamahant** [ellipsis-drive/arcgis-plugin#10]
1. Login as zara/Australia!007
2. Go to Shared with me
3. Observe that folder is not accessible (This is accessible in web app)

https://www.loom.com/share/d4170b536b0443d9b86946ffb92455e7

**Comment by B-Starkenburg** [comment]
I can't find the 'organization' map in the shared folder of zara. It could be the case that this was caused by the access check bug that was fixed earlier.
