### ISSUE TITLE
EDrive - Case - No access over folder

### ISSUE THREAD

**Issue by meghamahant** [ellipsis-drive/arcgis-plugin#11]
When the user does not have access over the folder (like the owner has revoked the access), the list in plugin says "access level too low".  I think it should say "No access" in this case.

1. Login as zara/Australia!007
2. Go to Favorites
3. Observe the issue mentioned above

Folder "Free Raster Data" is public. It should be accessible.

![Screenshot 2022-07-07 at 3 39 28 PM](https://user-images.githubusercontent.com/74825925/177749474-dd05acc1-df62-4eae-96ae-d6bd59656942.png)

![Screenshot 2022-07-07 at 3 40 55 PM](https://user-images.githubusercontent.com/74825925/177749663-ac08cdad-68fb-4ea3-b523-dfdf2cc0f19a.png)

**Comment by B-Starkenburg** [comment]
The access level check used an incorrect value. Could you check if it works now? It should be fixed.

**Comment by B-Starkenburg** [comment]
Also changed "access level to low" to "No access"

**Comment by meghamahant** [comment]
![Screenshot 2023-01-15 at 9 32 00 PM](https://user-images.githubusercontent.com/74825925/212552021-0d330d3b-7b6c-4f44-a99c-f8360e197cac.png)
