### ISSUE TITLE
EDrive - Rename map to layer

### ISSUE THREAD

**Issue by meghamahant** [ellipsis-drive/arcgis-plugin#13]
Since the term **Map** has been replaced with **Layer**, we should also do update in the plugin in order to maintain consistency.

 
![Screenshot 2022-10-11 at 1 15 52 PM](https://user-images.githubusercontent.com/74825925/195028784-139b947d-3cfa-4654-9276-61c579659868.png)

**Comment by B-Starkenburg** [comment]
Done

**Comment by meghamahant** [comment]
I do see the new features like **Search** and **Open in browser** but I am missing the rename in the new version of the plugin.

Example 👇 

![Screenshot 2023-01-09 at 12 48 50 PM](https://user-images.githubusercontent.com/74825925/211257751-adbee119-958e-4610-b257-69d4d8359bcd.png)

**Comment by B-Starkenburg** [comment]
This was also caused by me not updating the esri addin installer. It should be fixed now:
![image](https://user-images.githubusercontent.com/55835594/211284964-e8e554a8-f2c3-45eb-a38d-1cfc7dde324d.png)

**Comment by meghamahant** [comment]
![Screenshot 2023-01-15 at 7 22 45 PM](https://user-images.githubusercontent.com/74825925/212544777-1e1c1830-bec8-4b40-895a-da5e7e981472.png)
