### ISSUE TITLE
EDrive - Raster Layers can't be viewed

### ISSUE THREAD

**Issue by meghamahant** [ellipsis-drive/arcgis-plugin#15]
When you try to view the raster layer, the vector layer warning pops up blocking me to view the raster content.

https://www.loom.com/share/b2ec83f81c564e1bb4fdbf6b0acd6c00

**Comment by B-Starkenburg** [comment]
Previously, nodes that don't have a timestamp as node tag were always added as WFS layers, without checking the node protocol. 
I don't have a case where a node has a wmts protocol, without the node tag being a timestamp but I have added a check that should prevent this bug.

**Comment by meghamahant** [comment]
@B-Starkenburg 

I think it is still there.
More details in #8

**Comment by B-Starkenburg** [comment]
I believe this bug is fixed in a commit from a week ago. Could you check again, please?
