### ISSUE TITLE
EDrive - Raster Layer - WMS

### ISSUE THREAD

**Issue by meghamahant** [ellipsis-drive/arcgis-plugin#16]
**Issue:** When you select(double click) the WMS protocol,  it comes into the Layer panel but the raster data does not show up in the view.

Upon expanding the "Ellipsis Drive WMS" option it was found that the style was **UNselected** though "Ellipsis Drive WMS" was selected. I think the style should have been automatically selected so that user does not have to do it explicitly.

Example - https://www.loom.com/share/6f213ee799504300937552347b5aedcc

**Comment by B-Starkenburg** [comment]
WMS layers should now be automatically selected and visible
