### ISSUE TITLE
EDrive - Raster Layer - WMS, WMTS

### ISSUE THREAD

**Issue by meghamahant** [ellipsis-drive/arcgis-plugin#17]
Issue: 
I observed that when you select
- WMTS, the individual style is displayed in the layer panel
- but when you select the WMS, a tree structure is shown in the layer panel.

Why does the plugin have different behaviour for WMS and WMTS ? 

Example - https://www.loom.com/share/3475c495a81a4b28987f3813ca9410aa

![Screenshot 2023-01-15 at 9 04 52 PM](https://user-images.githubusercontent.com/74825925/212550564-83941266-c31e-4ef3-80de-d31f460ff292.png)

**Comment by B-Starkenburg** [comment]
This is the standard behavior of the ArcObjects methods that add the layers to the TOC. Currently I'm working on making an implementation so that the behavior of adding WMTS layers matches the behavior of adding WMS layers.

**Comment by B-Starkenburg** [comment]
I discussed with Daan how the structure should look like. We agreed on the following structure:
* Adding a WMS layer with all visualizations:

Ellipsis Drive WMS
|----"map name"
..........|----"timestamp name"
....................|----visualization 1
..............................|---- ....
..............................|---- visualization n

          
* Adding a single visualization WMS layer:
Ellipsis Drive WMS
|----"map_name"+"\_"+"timestamp_name"+"\_"+"visualization_name"

* Adding a WMTS layer with all visualizations:
Ellipsis Drive WMTS
|----"timestamp_name"+"\_"+"visualization_name1"
|---- ...
|----"timestamp_name"+"\_"+"visualization_name n"

* Adding a single visualization WMTS layer:
Ellipsis Drive WMTS
|----"timestamp_name"+"\_"+"visualization_name"


I tested it with a few layers and the convention should work and not break any logic preventing adding duplicate layers but it might help to do additional testing.

**Comment by meghamahant** [comment]
### Case 1 : Adding a WMS layer with all styles
![Screenshot 2023-02-08 at 4 34 40 PM](https://user-images.githubusercontent.com/74825925/217512282-81bb93b4-c326-4e41-b539-7163c77218f0.png)

### Case 2: Adding a single style WMS layer
![Screenshot 2023-02-08 at 4 36 32 PM](https://user-images.githubusercontent.com/74825925/217512691-d527bd5f-7b5e-4437-ae82-d50438b0f14a.png)

### Case 3: Adding a WMTS layer with all styles
![Screenshot 2023-02-08 at 4 38 12 PM](https://user-images.githubusercontent.com/74825925/217513074-2973c2bb-6896-4a7f-80b0-dd53a7ed016d.png)

### Case 4: Adding a single style WMTS layer
![Screenshot 2023-02-08 at 4 39 06 PM](https://user-images.githubusercontent.com/74825925/217513495-adaa586c-4cc1-4ebe-b9c8-ad839701d8b9.png)

**Comment by meghamahant** [comment]
Hi @B-Starkenburg,

The above cases are clear to me but the behaviour of the checkboxes is quite confusing. Could you help me in understanding the same for the cases where all the styles are selected.

**Case - Adding a timestamp with all styles.**
When I double click on WMS (multiple styles) >> All the styles are loaded in table of contents, all are checked.
But nothing appears in the view area.
I then start experimenting with the unchecking/checking of boxes to see in what situation the raster would appear.
I then noticed that when only one style was selected ad remaining were unselected, I got the raster in viewer.

Do you follow me ?
Here is the live example - https://www.loom.com/share/d69556a928c64e828f718456b6ea6653

**Comment by B-Starkenburg** [comment]
Hi @meghamahant,
I believe I am not able to fix this bug, since it is the standard behavior of adding WMS layers.
The same happens when I manually add a WMS service:
https://www.loom.com/share/c9b6034b1dcd4ff78a7a27d28678d2ce

**Comment by meghamahant** [comment]
Okay, so this seems to be a shortcoming of ArcMap then.

@danielvandermaas  - FYI.
