### ISSUE TITLE
EDrive - Vector Layer is not working

### ISSUE THREAD

**Issue by meghamahant** [ellipsis-drive/arcgis-plugin#18]
Issue - https://www.loom.com/share/5569df80f5744c9d9930f14518f974fa

**Comment by meghamahant** [comment]
Berend found evidence that ArcMap does not support vector layers.

**Comment by meghamahant** [comment]
The message will be adjusted to convey that ArcMap does not support vector layers.

**Comment by B-Starkenburg** [comment]
The error message is changed so it references ArcMap instead of ArcGIS Pro
