### ISSUE TITLE
EDrive - Map is shown as disabled

### ISSUE THREAD

**Issue by meghamahant** [ellipsis-drive/arcgis-plugin#2]
1. Login as admin
2. Go to Favorites
3. Observe that map `s2-elizabeth` is shown as disabled in the list.
4. In web app, it is active and admin can view it.

Mai Id - https://app.ellipsis-drive.com/view?mapId=849c2206-4d4f-42af-94d3-884067f39cb2

![Screenshot 2022-07-07 at 12 35 49 PM](https://user-images.githubusercontent.com/74825925/177712733-9d6806c8-e71f-43a3-948a-3258eec02b5d.png)

![Screenshot 2022-07-07 at 12 36 43 PM](https://user-images.githubusercontent.com/74825925/177712918-84cc36d3-0559-42e4-8009-54ef924526a5.png)

**Comment by danielvandermaas** [comment]
@B-Starkenburg  please call me to talk about the case handling here, there are many cases here

**Comment by B-Starkenburg** [comment]
@meghamahant s2-elizabeth is not shown as disabled in the list, but the map SOC is shown as disabled, however. I do not have accesss to that map, so could you check if SOC is actually disabled?
