### ISSUE TITLE
EDrive - Raster Map - Map with multiple layers

### ISSUE THREAD

**Issue by meghamahant** [ellipsis-drive/arcgis-plugin#4]
**Case:** If a map has more than one layer/visualizations, the plugin shows one layer only.

Example - This map has three layers but the plugin shows only one.
https://app.ellipsis-drive.com/view?mapId=78080fff-8bcb-4258-bb43-be9de956b3e0

![Screenshot 2022-07-07 at 10 41 48 AM](https://user-images.githubusercontent.com/74825925/177696425-d5b7f7de-40fd-4911-98fa-b1dcc355e2e6.png)

![Screenshot 2022-07-07 at 10 42 54 AM](https://user-images.githubusercontent.com/74825925/177696715-0e26dceb-0e2d-4b0b-a18a-b469e0a00d6a.png)

**Comment by B-Starkenburg** [comment]
The plugin now shows these multiple layers.
