### ISSUE TITLE
EDrive - Vector Maps

### ISSUE THREAD

**Issue by meghamahant** [ellipsis-drive/arcgis-plugin#6]
For the vector maps, as soon as I click on the vector layer I get an alert that vector layers are only supported in ArcGIS Pro. Is this a limitation of ArcMap ? Or is it something around the EDrive plugin ?
 
![Screenshot 2022-07-06 at 5 40 01 PM](https://user-images.githubusercontent.com/74825925/177547052-f9135ee0-70cb-4b9e-bab1-26082de96aff.png)

**Comment by B-Starkenburg** [comment]
@meghamahant There are no API calls to add vector layers since arcgis 10.3, so it is a limitation of ArcMap. I will clarify it in the notice message window.
