### ISSUE TITLE
EDrive - Naming the root folder

### ISSUE THREAD

**Issue by meghamahant** [ellipsis-drive/arcgis-plugin#7]
I think the naming should be consistent with the web app.
`Shared` should be `Shared with me`
 
![Screenshot 2022-07-07 at 1 25 22 PM](https://user-images.githubusercontent.com/74825925/177722124-b487d992-bd47-4b2f-9431-929ae81c4410.png)
![Screenshot 2022-07-07 at 1 25 06 PM](https://user-images.githubusercontent.com/74825925/177722137-c5ec0732-c855-4d29-a6aa-3233cbddd53e.png)

**Comment by B-Starkenburg** [comment]
Updated the root name frome "Shared" to "Shared with me"

**Comment by meghamahant** [comment]
ok.
