### ISSUE TITLE
EDrive - No possibility to access different timestamps

### ISSUE THREAD

**Issue by meghamahant** [ellipsis-drive/arcgis-plugin#8]
If a raster map has multiple timestamps, the web viewer allows you to access the one you want using the given slider.

Via EDrive, the list shows only one timestamp.

![Screenshot 2022-07-07 at 1 50 30 PM](https://user-images.githubusercontent.com/74825925/177727696-6399589e-6745-4da2-a436-78286528840c.png)

![Screenshot 2022-07-07 at 2 00 03 PM](https://user-images.githubusercontent.com/74825925/177728827-addf879c-5e7c-49a2-b6ac-7356324219ed.png)

**Comment by B-Starkenburg** [comment]
There was a bug that only one timestamp was added when a layer has multiple timestamps. This should be fixed now.

**Comment by meghamahant** [comment]
@B-Starkenburg 

I think something is not right here. When I double click on the raster timestamp, I get an error message around the vector layer.

Example - https://www.loom.com/share/3f74e59687fb4476af660a2702df3763

**Comment by B-Starkenburg** [comment]
I fixed the bug where this message pops up. The current behavior is that double clicking on a timestamp only expands or collapses that node but no layer is added to the TOC.
